spring:
  redis:
#    cluster:
#      nodes: 10.100.51.65:7001,10.100.51.65:7002,10.100.51.65:7003,10.100.51.65:7004,10.100.51.65:7005,10.100.51.65:7006
    database: 0 #redis数据库索引，默认为0
    host: 10.100.50.141 #redis服务器地址
    port: 7001 #redis服务器连接端口
    password: #redis服务器连接密码，默认为null
    timeout: 5000 #redis连接超时时间

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/limit?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: root

#mybatis-plus配置
mybatis-plus:
  #项目启动会检查xml配置存在(只在开发时候打开)
  check-config-location: true
  #xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath*:com/wj/limit/**/mapper/*Mapper.xml
  #实体路径
  type-aliases-package: com.wj.limit.entity
  configuration:
    #全局地开启或关闭配置文件中的所有映射器已经配置的任何缓存，默认为 true
    cache-enabled: true
    #开启驼峰转下滑
    map-underscore-to-camel-case: true
    #如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    #这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      #表名下划线命名默认true
      table-underline: true
      #id类型
      id-type: auto
      #是否开启大写命名，默认不开启
      #capital-mode: false
      #逻辑未删除值,(逻辑删除下有效) 需要注入逻辑策略LogicSqlInjector 以@Bean方式注入
      logic-not-delete-value: 0
      #逻辑已删除值,(逻辑删除下有效)
      logic-delete-value: 1
      #数据库类型
  #      db-type: sql_server